apiVersion: apps/v1
kind: Deployment
metadata:
  name: cherry-go-client
  labels:
    app: cherry-go-client
spec:
  selector: 
    matchLabels:
      app: cherry-go-client 
  replicas: 2
  template:
    metadata:
      labels:
        app: cherry-go-client 
    spec:
      containers:
        - name: cherry-go-client
          image: "andersonfrfilho/cherry-go-web-client:ebb68bd"
          resources:
            requests: 
              cpu: "250m"
              memory: 300Mi
            limits: 
              cpu: 500m
              memory: 600Mi 
          startupProbe: 
            httpGet:
              path: '/'
              port: 3000 
            periodSeconds: 3 
            failureThreshold: 30 
          readinessProbe: 
            httpGet:
              path: '/'
              port: 3000 
            periodSeconds: 3 
            failureThreshold: 1 
          livenessProbe:
            httpGet: 
              path: '/'
              port: 3000 
            periodSeconds: 5 
            failureThreshold: 1 
            timeoutSeconds: 1 
            successThreshold: 1 
          envFrom:
            - configMapRef:
                name: cherry-go-client-env
            - secretRef:
                name: cherry-go-client-secret-env
      imagePullSecrets:
      - name: regcred
