apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cherry-go-client-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: cherry-go-client
    kind: Deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30