apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: 
  name: letsencrypt-homolog
  namespace: cert-manager
spec: 
  acme: 
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@cherry-go.com
    privateKeySecretRef:
      name: letsencrypt-homolog
    solvers: 
      - http01: 
          ingress: 
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: 
  name: letsencrypt-prod
spec: 
  acme: 
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@cherry-go.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers: 
      - http01: 
          ingress: 
            class: nginx