apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cherry-go-staging-ingress-hosts
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    ingress.kubernetes.io/force-ssl.redirect: "true"
spec:
  rules:
  - host: "staging.api.cherry-go.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cherry-go-api-service
            port: 
              number: 80
  - host: "staging.painel.cherry-go.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cherry-go-backoffice-service
            port: 
              number: 80
  - host: "staging.cherry-go.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cherry-go-client-service
            port: 
              number: 80
  tls: 
  - hosts: 
    - staging.api.cherry-go.com
    - staging.painel.cherry-go.com
    - staging.cherry-go.com
    secretName: cherry-go-staging-letsencrypt