apiVersion: v1
kind: Secret
metadata:
  name: cherry-go-secret-env
type: Opaque
data:
  PASSWORD_USER_SEED_HASH: YURTYm1ucnV6Tlpka3pBL2tLZUtDLjVNTW04SmQwZjRKdUVqSFU1V1V2WUwwT2xaMlpObm0=
  HASH_TOKEN: ODliYTAyMzA4NmUzN2EzNDU4MzllMGM2YTBkMjcyZWI=
  HASH_REFRESH_TOKEN: YTdlMDcxYjNkZTQ4Y2VjMWRkMjRkZTZjYmU2YzdiZjE=
  AWS_ACCESS_KEY_ID: QUtJQTNGS0xHWE1DT1JZR1EyVUg=
  AWS_SECRET_ACCESS_KEY: b3RVbm1kcmJLQ3krN1hFeUczV3VBZ25LYmd6bU1NU1IvcmdKQjZHeQ==
  POSTGRES_PASSWORD: Y2hlcnJ5X2dvX3B3ZA==
  SMS_API_KEY: OGY4ZWJkNDg=
  SMS_API_SECRET: R2pCWTBEdWpxTmJuUUNwVA==