apiVersion: v1
kind: Service
metadata:
  name: cherry-go-backoffice-service
spec:
  selector: 
    app: cherry-go-backoffice
  type: ClusterIP 
  ports:
  - name:  cherry-go-backoffice-service-port
    port: 80 
    targetPort: 3000 
    protocol: TCP
