apiVersion: v1
kind: ConfigMap
metadata:
  name: cherry-go-worker-env
data:
  ENVIRONMENT: "staging"
  PORT: "3333"
  TZ: "UTC"
  DATE_PROVIDER: "dateFns"
  FORGOT_MAIL_URL: "http://cherry-go-backend-service:33333/v1/users/password/reset?token="
  FORGOT_MOBILE_URL: "cherry-go://app/reset-password/"
  CONFIRM_MAIL_URL: "http://cherry-go-backend-service:3333/v1/users/confirm/mail?token="
  TOKEN_EXPIRATION_TIME_MAIL_CONFIRMATION: "30"

  ## QUEUE
  QUEUE_BASE_URL_BROKER: "cherry-go-kafka.cherry-go-kafka.svc.cluster.local:9092"
  QUEUE_PROVIDER: "kafka"

  ## AWS Credentials
  AWS_DEFAULT_REGION: "us-east-1"

  ## AWS Bucket
  AWS_BUCKET: "cherry-go-bucket-stg"
  AWS_BUCKET_REGION: "us-east-1"
  AWS_BUCKET_URL: ""
  # {dev:localhost:3333, prod:https://api-rentx-andersonfrfilho.s3.amazonaws.com }
  STORAGE_URL: "http://cherry-go-backend-service:3333"

  ##Storage Optional { dev: local, prod: s3 }
  DISK_STORAGE_PROVIDER: "local"
  ##Email Optional { dev: etheral, prod: ses }
  MAIL_PROVIDER: "ses"

  # Postgres
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "postgres-cherry-go-service"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "cherry_go"
  # POSTGRES TEST
  POSTGRES_PORT_TEST: "5434"
  POSTGRES_DB_TEST: "cherry_go_test"

  # Mongo
  MONGO_HOST: "mongo-cherry-go-service"
  MONGO_PORT: "27017"
  MONGO_DATABASE: "cherry_go"
  MONGO_TEST_DB: "cherry_go"

  # Redis
  REDIS_HOST: "redis-cherry-go-service"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  # Sentry
  SENTRY_DSN: "https://be585c9462224567bb62e38ecfa48ef1@o296769.ingest.sentry.io/5734148"

  # SMS COMMUNICATION
  # SMS_COMMUNICATION=true
  SMS_PROVIDER: "vonage"

