apiVersion: apps/v1
kind: Deployment
metadata:
  name: cherry-go-worker 
  labels:
    app: cherry-go-worker
spec:
  selector: 
    matchLabels:
      app: cherry-go-worker 
  replicas: 1
  template:
    metadata:
      labels:
        app: cherry-go-worker 
    spec:
      containers:
        - name: cherry-go-worker-container
          image: "andersonfrfilho/cherry-go-worker:8e6dc93"
          resources:
            requests: 
              cpu: "200m"
              memory: 200Mi
            limits: 
              cpu: 500m
              memory: 400Mi 
          startupProbe: 
            httpGet:
              path: '/healthcheck'
              port: 3334 
            periodSeconds: 3 
            failureThreshold: 30 
          readinessProbe: 
            httpGet:
              path: '/healthcheck'
              port: 3334
            periodSeconds: 3 
            failureThreshold: 1 
          livenessProbe:
            httpGet: 
              path: '/healthcheck'
              port: 3334 
            periodSeconds: 5 
            failureThreshold: 1 
            timeoutSeconds: 1 
            successThreshold: 1 
          envFrom:
            - configMapRef:
                name: cherry-go-worker-env
            - secretRef:
                name: cherry-go-worker-secret-env
