apiVersion: apps/v1
kind: Deployment
metadata:
  name: cherry-go-worker 
  labels:
    app: cherry-go-worker
spec:
  selector: 
    matchLabels:
      app: cherry-go-worker 
  replicas: 2
  template:
    metadata:
      labels:
        app: cherry-go-worker 
    spec:
      containers:
        - name: cherry-go-worker-container
          image: "andersonfrfilho/cherry-go_worker_backend:1.0.0"
          resources:
            requests: 
              cpu: "0.3"
              memory: 20Mi 
            limits: 
              cpu: 500m
              memory: 25Mi 
          startupProbe: 
            httpGet:
              path: '/healthz'
              port: 3000 
            periodSeconds: 3 
            failureThreshold: 30 
          readinessProbe: 
            httpGet:
              path: '/healthz'
              port: 3000 
            periodSeconds: 3 
            failureThreshold: 1 
          livenessProbe:
            httpGet: 
              path: '/healthz'
              port: 3000 
            periodSeconds: 5 
            failureThreshold: 1 
            timeoutSeconds: 1 
            successThreshold: 1 
          envFrom:
            - configMapRef:
                name: cherry-go-worker-env
            - secretRef:
                name: cherry-go-worker-secret-env
