apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cherry-go-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: cherry-go-worker
    kind: Deployment
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 30