apiVersion: v1
kind: Service
metadata:
  name: cherry-go-worker-service
spec:
  selector: 
    app: cherry-go-worker
  type: ClusterIP 
  ports:
  - name:  cherry-go-worker-service-port
    port: 80 
    targetPort: 3334 
    protocol: TCP