kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cherry-go-mongo-pv-claim
  labels:
    app: cherry-go-mongo-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi