kind: PersistentVolume
apiVersion: v1
metadata:
  name: cherry-go-mongo-pv-volume
  labels:
    type: local
    app: cherry-go-mongo-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"