apiVersion: v1
kind: Service
metadata:
  name: mongo-cherry-go-service
spec:
  selector:
    app: mongo-cherry-go
  type: ClusterIP
  ports:
    - name: mongo-cherry-go-service-port
      port: 27017
      protocol: TCP