apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  replicas: 4
  serviceName: mongo-service
  selector:
      matchLabels:
        app: mongo-cherry-go 
  template:
    metadata:
      labels:
        app: mongo-cherry-go
    spec:
      containers:
        - name: mongo-container
          image: mongo
          envFrom:
            - configMapRef:
                name: cherry-go-env
            - secretRef:
                name: cherry-go-secret-env
          volumeMounts:
            - mountPath: /data/mongo
              name: mongo-volume

  volumeClaimTemplates:
  - metadata:
      name: mongo-volume
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi