apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: redis-cherry-go-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: redis
    kind: Deployment
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 30