apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: redis-cherry-go
spec:
  selector:
    matchLabels:
      app: redis-cherry-go
  replicas: 2
  template:
    metadata:
      labels:
        app: redis-cherry-go
    spec:
      containers:
        - name: master
          image: k8s.gcr.io/redis
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits: 
              cpu: 500m
              memory: 500Mi 
          ports:
          - containerPort: 6379
          envFrom:
            - configMapRef:
                name: cherry-go-api-env
            - secretRef:
                name: cherry-go-api-secret-env