apiVersion: v1
kind: ConfigMap
metadata:
  name: cherry-go-api-env
data:
  ENVIRONMENT: "staging"
  PORT: "3333"
  TZ: "UTC"
  DATE_PROVIDER: "dateFns"
  FORGOT_MAIL_URL: "https://staging.cherry-go.com/v1/users/password/reset?token="
  FORGOT_MOBILE_URL: "cherry-go://app/reset-password/"
  CONFIRM_MAIL_URL: "https://staging.cherry-go.com/v1/users/confirm/mail?token="
  TOKEN_EXPIRATION_TIME_MAIL_CONFIRMATION: "30"
  EXPIRE_IN_TOKEN: "7d"

  ## QUEUE
  QUEUE_BASE_URL_BROKER: "cherry-go-kafka-0.cherry-go-kafka-headless.cherry-go-kafka.svc.cluster.local:9092"
  QUEUE_PROVIDER: "kafka"

  ## AWS Credentials
  AWS_DEFAULT_REGION: "us-east-1"

  ## AWS Credentials SMTP
  AWS_SMTP_ACCESS_KEY_ID: "AKIA3FKLGXMCMBYWY47N"

  ## SMS PROVIDER CREDENTIALS (SNS)
  AWS_SNS_ACCESS_KEY_ID: "AKIA3FKLGXMCIICXDNQF"

  ## AWS Bucket
  STORAGE_PROVIDER: "s3"
  AWS_BUCKET_ACCESS_KEY_ID: "AKIA3FKLGXMCHWHEZVHA"
  
  AWS_BUCKET_NAME: "cherry-go-bucket-staging"
  AWS_BUCKET_REGION: "us-east-1"
 
  STORAGE_URL: "https://staging.cherry-go.com/v1"

  ##Storage Optional { dev: local, prod: s3 }
  DISK_STORAGE_PROVIDER: "local"
  ##Email Optional { dev: etheral, prod: ses }
  MAIL_PROVIDER: "ses"

  # Postgres
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "postgres-cherry-go-service"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "cherry_go"
  PGTZ: "America/Sao_Paulo"
  # POSTGRES TEST
  POSTGRES_PORT_TEST: "5434"
  POSTGRES_DB_TEST: "cherry_go_test"

  # Mongo
  MONGO_HOST: "mongo-cherry-go-service"
  MONGO_PORT: "27017"
  MONGO_DATABASE: "cherry_go"
  MONGO_TEST_DB: "cherry_go"

  # Redis
  CACHE_DRIVER: "redis"
  CACHE_URL: "cherry-go-redis-master.default.svc.cluster.local"
  CACHE_PORT: "6379"
  # Sentry
  SENTRY_DSN: "https://be585c9462224567bb62e38ecfa48ef1@o296769.ingest.sentry.io/5734148"

  # SMS COMMUNICATION
  # SMS_COMMUNICATION=true
  SMS_PROVIDER: "vonage"

