apiVersion: apps/v1
kind: Deployment
metadata:
  name: cherry-go-api
  labels:
    app: cherry-go-api
spec:
  selector: 
    matchLabels:
      app: cherry-go-api 
  replicas: 2
  template:
    metadata:
      labels:
        app: cherry-go-api 
    spec:
      containers:
        - name: cherry-go-api
          image: "andersonfrfilho/cherry-go-api:1b74749"
          resources:
            requests: 
              cpu: "200m"
              memory: 200Mi
            limits: 
              cpu: 500m
              memory: 400Mi 
          startupProbe: 
            httpGet:
              path: '/healthcheck'
              port: 3333 
            periodSeconds: 3 
            failureThreshold: 30 
          readinessProbe: 
            httpGet:
              path: '/healthcheck'
              port: 3333 
            periodSeconds: 3 
            failureThreshold: 1 
          livenessProbe:
            httpGet: 
              path: '/healthcheck'
              port: 3333 
            periodSeconds: 5 
            failureThreshold: 1 
            timeoutSeconds: 1 
            successThreshold: 1 
          envFrom:
            - configMapRef:
                name: cherry-go-api-env
            - secretRef:
                name: cherry-go-api-secret-env
      imagePullSecrets:
      - name: regcred
